//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiethoadonnhap
    {
        public string mahdn { get; set; }
        public string mamh { get; set; }
        public Nullable<decimal> soluongnhap { get; set; }
        public Nullable<decimal> dongianhap { get; set; }
    
        public virtual Chitiethoadonnhap Chitiethoadonnhap1 { get; set; }
        public virtual Chitiethoadonnhap Chitiethoadonnhap2 { get; set; }
        public virtual HoaDonNhap HoaDonNhap { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
