//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiethoadonban
    {
        public string mahdb { get; set; }
        public string mamh { get; set; }
        public Nullable<decimal> soluongban { get; set; }
        public Nullable<decimal> dongiaban { get; set; }
    
        public virtual Chitiethoadonban Chitiethoadonban1 { get; set; }
        public virtual Chitiethoadonban Chitiethoadonban2 { get; set; }
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
