//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doanhthunam
    {
        public Nullable<int> Năm { get; set; }
        public Nullable<int> Tháng { get; set; }
        public Nullable<decimal> tongsoluongban { get; set; }
        public Nullable<decimal> Doanhthu { get; set; }
        public string mahdb { get; set; }
        public string manv { get; set; }
        public string mamh { get; set; }
    }
}
