//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doanhthuquy
    {
        public string mahdb { get; set; }
        public string mamh { get; set; }
        public Nullable<decimal> soluongban { get; set; }
        public Nullable<decimal> dongiaban { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<int> Quý { get; set; }
        public Nullable<System.DateTime> ngayban { get; set; }
        public Nullable<int> Năm { get; set; }
    }
}
