//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonNhap()
        {
            this.Chitiethoadonnhap = new HashSet<Chitiethoadonnhap>();
        }
    
        public string mahdn { get; set; }
        public string manv { get; set; }
        public string mancc { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiethoadonnhap> Chitiethoadonnhap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
