//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.Chitiethoadonban = new HashSet<Chitiethoadonban>();
            this.Chitiethoadonnhap = new HashSet<Chitiethoadonnhap>();
        }
    
        public string mamh { get; set; }
        public string tenmh { get; set; }
        public string tenncc { get; set; }
        public Nullable<int> namsx { get; set; }
        public Nullable<decimal> tonkho { get; set; }
        public Nullable<decimal> dongia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiethoadonban> Chitiethoadonban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiethoadonnhap> Chitiethoadonnhap { get; set; }
    }
}
