//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBHMyPhamEntities : DbContext
    {
        public QLBHMyPhamEntities()
            : base("name=QLBHMyPhamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chitiethoadonban> Chitiethoadonban { get; set; }
        public virtual DbSet<Chitiethoadonnhap> Chitiethoadonnhap { get; set; }
        public virtual DbSet<HoaDonBan> HoaDonBan { get; set; }
        public virtual DbSet<HoaDonNhap> HoaDonNhap { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<MatHang> MatHang { get; set; }
        public virtual DbSet<NCC> NCC { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Doanhthunam> Doanhthunam { get; set; }
        public virtual DbSet<Doanhthuquy> Doanhthuquy { get; set; }
        public virtual DbSet<Doanhthuthang> Doanhthuthang { get; set; }
    }
}
